CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(120) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

ALTER TABLE articles ADD COLUMN user_id VARCHAR(36) NULL;
ALTER TABLE moments ADD COLUMN user_id VARCHAR(36) NULL;
ALTER TABLE albums ADD COLUMN user_id VARCHAR(36) NULL;
ALTER TABLE album_photos ADD COLUMN user_id VARCHAR(36) NULL;
ALTER TABLE categories ADD COLUMN user_id VARCHAR(36) NULL;
ALTER TABLE tags ADD COLUMN user_id VARCHAR(36) NULL;
ALTER TABLE memory_capsules ADD COLUMN user_id VARCHAR(36) NULL;
ALTER TABLE settings ADD COLUMN user_id VARCHAR(36) NULL;

CREATE TABLE IF NOT EXISTS inspirations (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  type VARCHAR(80) NULL,
  status VARCHAR(80) NULL,
  tags JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS mood_records (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NULL,
  date DATE NOT NULL,
  mood VARCHAR(80) NOT NULL,
  weather VARCHAR(80) NULL,
  note TEXT NULL,
  related_article_ids JSON NULL,
  related_moment_ids JSON NULL,
  related_gallery_ids JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS locations (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(36) NULL,
  name VARCHAR(255) NOT NULL,
  city VARCHAR(120) NULL,
  country VARCHAR(120) NULL,
  latitude DECIMAL(10, 7) NULL,
  longitude DECIMAL(10, 7) NULL,
  description TEXT NULL,
  cover_image TEXT NULL,
  related_article_ids JSON NULL,
  related_moment_ids JSON NULL,
  related_gallery_ids JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);
